name: Filmshape
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
#  upgrader: ^0.7.0
  dio: ^3.0.6
  intl: ^0.16.1
  shared_preferences: ^0.5.6
  cached_network_image: ^2.0.0-rc.1
  font_awesome_flutter: ^8.8.1
  image_picker: ^0.6.3+4
  image_cropper: ^1.2.1
  flutter_tags: ^0.3.0
  flutter_svg: ^0.17.3+1
  provider: ^3.0.0+1


#  rxdart: ^0.22.1
#  youtube_player_flutter: ^6.0.3+2
  youtube_api: ^0.7.2
  flutter_appauth:
  material_search: ^0.2.8
  flutter_masked_text: ^0.8.0
  flutter_google_places: ^0.2.1
#  flutter_screenutil: ^1.0.2
#  flutter_recaptcha_v2: ^0.1.0
#  like_button: ^0.2.0
#  webview_flutter: ^0.3.21
  flutter_webview_plugin: ^0.3.11
#  custom_navigator: ^0.3.0
  notifier: ^1.0.2
  youtube_player_flutter: ^6.1.0+4
  url_launcher: ^5.4.7
  flutter_inappwebview: ^3.3.0
  flutter_local_notifications: ^1.1.6
  firebase_messaging: ^6.0.9
  firebase_auth:
  firebase_core:
  share: ^0.6.4+3
  flutter_html: ^0.11.1
  badges: ^1.1.1
  cloud_firestore: ^0.13.7
  firebase_storage: ^3.1.6
  flutter_linkify: ^3.1.3
  tuple: ^1.0.3
  social_share: ^2.0.5

  flutter_widgets: ^0.1.12
  package_info: ^0.4.1
  flutter_spinkit: ^4.1.2+1
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/tutorial/
    - assets/icons/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:

    - family: LatoBold
      fonts:
        - asset: fonts/Lato-Bold.ttf

    - family: LatoReguler
      fonts:
        - asset: fonts/Lato-Regular.ttf

    - family: LatoSemiBold
      fonts:
        - asset: fonts/Lato-Semibold.ttf


    - family: LatoLight
      fonts:
        - asset: fonts/Lato-Light.ttf

    - family: LatoThin
      fonts:
        - asset: fonts/Lato-Thin.ttf

    - family: MuliBold
      fonts:
        - asset: fonts/Muli ExtraBold.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
